import "./styles.css";

type Item = { id: string; name: string; category: string; status: "Published" | "Draft"; updated: string; owner: string };

const seed: Item[] = [
  { id: "mat_00001", name: "Iron Ore", category: "Material", status: "Published", updated: "Today, 09:24", owner: "Content team" },
  { id: "gear_00187", name: "Hunter's Longbow", category: "Equipment", status: "Published", updated: "Yesterday", owner: "Content team" },
  { id: "cons_00004", name: "Minor Healing Potion", category: "Consumable", status: "Draft", updated: "Jul 28, 2026", owner: "Linh Nguyen" },
  { id: "rune_00021", name: "Rune of Swiftness", category: "Rune", status: "Published", updated: "Jul 26, 2026", owner: "Content team" },
];

const icon = (path: string) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="h-5 w-5">${path}</svg>`;
const nav = (active = "Items") => [
  ["Overview", icon('<path d="M4 13h6V4H4v9Zm0 7h6v-5H4v5Zm10 0h6v-9h-6v9Zm0-16v4h6V4h-6Z"/>')],
  ["Items", icon('<path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Zm0 9 8-4.5M12 12v9M4 7.5 12 12"/>')],
  ["Players", icon('<path d="M16 20v-1.5a4.5 4.5 0 0 0-4.5-4.5h-3A4.5 4.5 0 0 0 4 18.5V20m6-10a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm6-5h4m-2-2v4"/>')],
  ["Content releases", icon('<path d="M5 4h14v16H5zM8 8h8m-8 4h8m-8 4h5"/>')],
  ["Audit log", icon('<path d="M4 5h16M4 12h16M4 19h10"/>')],
].map(([label, glyph]) => `<button class="nav-item ${label === active ? "active" : ""}" data-nav="${label}">${glyph}<span>${label}</span></button>`).join("");

const app = document.querySelector<HTMLDivElement>("#app")!;
let items = [...seed];
let query = "";
let adminUsername = localStorage.getItem("admin_user") ?? "admin";
let adminPassword = "";
localStorage.removeItem("admin_password");

function render() {
  const filtered = items.filter((item) => `${item.id} ${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
  app.innerHTML = `<div class="flex min-h-screen">
    <aside class="hidden w-64 shrink-0 border-r border-slate-800 bg-[#07111f] text-slate-300 lg:flex lg:flex-col">
      <div class="flex h-20 items-center gap-3 border-b border-white/10 px-6"><div class="grid h-9 w-9 place-items-center rounded-xl bg-cyan-400 font-black text-slate-950">EH</div><div><p class="text-sm font-semibold text-white">Evil Hunter</p><p class="text-[11px] text-slate-500">Operations console</p></div></div>
      <div class="px-4 pt-7"><p class="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-slate-600">Workspace</p><nav class="space-y-1">${nav()}</nav></div>
      <div class="mt-auto border-t border-white/10 p-4"><div class="flex items-center gap-3 rounded-xl bg-white/5 p-3"><div class="grid h-8 w-8 place-items-center rounded-full bg-cyan-400/15 text-xs font-bold text-cyan-300">AD</div><div class="min-w-0"><p class="truncate text-xs font-semibold text-white">Admin</p><p class="truncate text-[11px] text-slate-500">Content manager</p></div></div></div>
    </aside>
    <main class="min-w-0 flex-1"><header class="flex h-20 items-center justify-between border-b border-slate-200 bg-white px-5 sm:px-8"><div><p class="text-xs font-semibold uppercase tracking-[.16em] text-cyan-600">Content management</p><h1 class="mt-1 text-xl font-bold tracking-tight text-slate-900">Items</h1></div><div class="flex items-center gap-3"><span id="api-status" class="hidden items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700 sm:flex"><span class="h-1.5 w-1.5 rounded-full bg-emerald-500"></span>Server connected</span><button class="rounded-lg border border-slate-200 p-2 text-slate-500 hover:bg-slate-50">${icon('<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4"/>')}</button></div></header>
      <div class="mx-auto max-w-[1440px] p-5 sm:p-8"><div class="mb-7 grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold text-slate-500">Total items</p><p class="mt-2 text-3xl font-bold text-slate-900">369</p><p class="mt-1 text-xs text-emerald-600">+12 this release</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold text-slate-500">Published</p><p class="mt-2 text-3xl font-bold text-slate-900">${items.filter((i) => i.status === "Published").length}</p><p class="mt-1 text-xs text-slate-500">Active in production</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold text-slate-500">Draft changes</p><p class="mt-2 text-3xl font-bold text-slate-900">${items.filter((i) => i.status === "Draft").length}</p><p class="mt-1 text-xs text-amber-600">Awaiting review</p></div></div>
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-col gap-4 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold text-slate-900">Item catalog</h2><p class="mt-1 text-xs text-slate-500">Manage game definitions in the current draft release.</p></div><button id="create" class="inline-flex items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-slate-700">${icon('<path d="M12 5v14m-7-7h14"/>')} Add item</button></div><div class="flex flex-col gap-3 border-b border-slate-100 bg-slate-50/70 p-4 sm:flex-row"><label class="relative flex-1"><span class="sr-only">Search items</span><span class="pointer-events-none absolute left-3 top-2.5 text-slate-400">${icon('<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>')}</span><input id="search" value="${query}" placeholder="Search by name or ID..." class="w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none ring-cyan-500 focus:ring-2" /></label><select class="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-600 outline-none"><option>All categories</option><option>Material</option><option>Equipment</option><option>Consumable</option></select><select class="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-600 outline-none"><option>All statuses</option><option>Published</option><option>Draft</option></select></div><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-slate-50 text-[11px] font-bold uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Item</th><th class="px-5 py-3">Category</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Last updated</th><th class="px-5 py-3">Owner</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">${filtered.map(row).join("") || '<tr><td colspan="6" class="px-5 py-12 text-center text-slate-500">No items match your search.</td></tr>'}</tbody></table></div><div class="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-xs text-slate-500"><span>Showing 1–${filtered.length} of ${items.length} items</span><div class="flex gap-1"><button class="rounded border border-slate-200 px-3 py-1.5 hover:bg-slate-50">Previous</button><button class="rounded border border-slate-200 bg-slate-900 px-3 py-1.5 text-white">1</button><button class="rounded border border-slate-200 px-3 py-1.5 hover:bg-slate-50">2</button><button class="rounded border border-slate-200 px-3 py-1.5 hover:bg-slate-50">Next</button></div></div></section></div></main></div>`;
  bind();
}

function row(item: Item) { return `<tr class="group hover:bg-slate-50/70"><td class="px-5 py-4"><div class="flex items-center gap-3"><div class="grid h-9 w-9 place-items-center rounded-lg bg-cyan-50 text-xs font-bold text-cyan-700">${item.name.slice(0, 2).toUpperCase()}</div><div><p class="font-semibold text-slate-800">${item.name}</p><p class="mt-0.5 font-mono text-[11px] text-slate-400">${item.id}</p></div></div></td><td class="px-5 py-4 text-slate-600">${item.category}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-[11px] font-bold ${item.status === "Published" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}">${item.status}</span></td><td class="px-5 py-4 text-slate-500">${item.updated}</td><td class="px-5 py-4 text-slate-600">${item.owner}</td><td class="px-5 py-4 text-right"><button data-edit="${item.id}" class="rounded-md p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700">${icon('<path d="m14 6 4 4M4 20l1-4L16 5a2.8 2.8 0 0 1 4 4L9 20H4Z"/>')}</button><button data-delete="${item.id}" class="rounded-md p-2 text-slate-400 hover:bg-red-50 hover:text-red-600">${icon('<path d="M4 7h16m-10 4v5m4-5v5M6 7l1 13h10l1-13M9 7V4h6v3"/>')}</button></td></tr>`; }

function bind() { document.querySelector<HTMLInputElement>("#search")?.addEventListener("input", (e) => { query = (e.target as HTMLInputElement).value; render(); }); document.querySelector("#create")?.addEventListener("click", () => openModal()); document.querySelectorAll<HTMLButtonElement>("[data-delete]").forEach((button) => button.addEventListener("click", () => { items = items.filter((item) => item.id !== button.dataset.delete); render(); })); document.querySelectorAll<HTMLButtonElement>("[data-edit]").forEach((button) => button.addEventListener("click", () => openModal(items.find((item) => item.id === button.dataset.edit)))); }
function openModal(item?: Item) { const editing = Boolean(item); const modal = document.createElement("div"); modal.className = "fixed inset-0 z-10 grid place-items-center bg-slate-950/40 p-4"; modal.innerHTML = `<form class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div class="flex items-start justify-between"><div><h3 class="text-lg font-bold text-slate-900">${editing ? "Edit item" : "Create item"}</h3><p class="mt-1 text-xs text-slate-500">Changes are saved to the current draft release.</p></div><button type="button" class="close text-2xl leading-none text-slate-400">&times;</button></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><label class="text-xs font-semibold text-slate-600">Item ID<input name="id" required ${editing ? "readonly" : ""} value="${item?.id ?? ""}" class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm ${editing ? "bg-slate-50" : ""}" /></label><label class="text-xs font-semibold text-slate-600">Name<input name="name" required value="${item?.name ?? ""}" class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label><label class="text-xs font-semibold text-slate-600">Category<select name="category" class="mt-2 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option ${item?.category === "Material" ? "selected" : ""}>Material</option><option ${item?.category === "Equipment" ? "selected" : ""}>Equipment</option><option ${item?.category === "Consumable" ? "selected" : ""}>Consumable</option><option ${item?.category === "Rune" ? "selected" : ""}>Rune</option></select></label><label class="text-xs font-semibold text-slate-600">Status<select name="status" class="mt-2 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option ${item?.status === "Published" ? "selected" : ""}>Published</option><option ${item?.status === "Draft" || !item ? "selected" : ""}>Draft</option></select></label></div><div class="mt-7 flex justify-end gap-3"><button type="button" class="close rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-600">Cancel</button><button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Save changes</button></div></form>`; document.body.append(modal); modal.querySelectorAll(".close").forEach((button) => button.addEventListener("click", () => modal.remove())); modal.querySelector("form")!.addEventListener("submit", (event) => { event.preventDefault(); const data = new FormData(event.currentTarget as HTMLFormElement); const next = { id: String(data.get("id")), name: String(data.get("name")), category: String(data.get("category")), status: String(data.get("status")) as Item["status"], updated: "Just now", owner: "Admin" }; items = editing ? items.map((current) => current.id === item!.id ? next : current) : [next, ...items]; modal.remove(); render(); }); }

function checkAdminAccess() {
  if (!adminPassword) {
    showLogin();
    return;
  }
  requestWithStoredCredentials().then((response) => { if (response.status === 401) showLogin(); else if (!response.ok) markDisconnected(); }).catch(markDisconnected);
}

function markDisconnected() { document.querySelector("#api-status")?.classList.replace("text-emerald-700", "text-amber-700"); document.querySelector("#api-status")?.querySelector("span:last-child")?.replaceWith("Server unavailable"); }

function showLogin() {
  const modal = document.createElement("div");
  modal.className = "fixed inset-0 z-20 grid place-items-center bg-[#07111f]/80 p-4";
  modal.innerHTML = `<form class="w-full max-w-sm rounded-2xl bg-white p-7 shadow-2xl"><div class="mb-6"><div class="mb-4 grid h-10 w-10 place-items-center rounded-xl bg-cyan-400 font-black text-slate-950">EH</div><h2 class="text-xl font-bold text-slate-900">Sign in to operations</h2><p class="mt-1 text-sm text-slate-500">Use the temporary admin credentials configured on the server.</p></div><label class="block text-xs font-semibold text-slate-600">Username<input name="username" autocomplete="username" required value="${adminUsername}" class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label><label class="mt-4 block text-xs font-semibold text-slate-600">Password<input name="password" type="password" autocomplete="current-password" required class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label><p class="error mt-3 hidden text-xs font-medium text-red-600">Invalid credentials.</p><button class="mt-6 w-full rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Continue</button></form>`;
  document.body.append(modal);
  modal.querySelector("form")!.addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget as HTMLFormElement); adminUsername = String(data.get("username")); adminPassword = String(data.get("password")); localStorage.setItem("admin_user", adminUsername); const response = await requestWithStoredCredentials(); if (response.ok) modal.remove(); else { adminPassword = ""; modal.querySelector(".error")?.classList.remove("hidden"); } });
}

function requestWithStoredCredentials() { return fetch("/admin/overview", { headers: { Authorization: `Basic ${btoa(`${adminUsername}:${adminPassword}`)}` } }); }

render();
checkAdminAccess();
