// Generated by tools/generate-protocol.mjs. Do not edit directly.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::{BottomMenuIntent, OriginalFlowSnapshot};

pub const PROTOCOL_VERSION: u16 = 5;
pub const MAX_MESSAGE_BYTES: usize = 16384;

#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case", deny_unknown_fields)]
pub enum ClientCommand {
    CompleteBoot,
    SelectBottomMenu { menu: BottomMenuIntent },
    NavigateBack,
    EnterField,
    SelectEntity { entity_id: String },
    OpenHunterProgression { hunter_id: u32 },
    EquipHunterItem { hunter_id: u32, item_id: u32 },
    ClaimQuestReward { quest_id: String },
    OpenShop { shop_id: String },
    PurchaseShopItem { shop_id: String, product_id: String },
    ClaimMail { mail_id: String },
    ClaimRewardedAd { placement: String },
    StartTopupPurchase { product_id: String },
    RequestResync,
}

#[derive(Debug, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMessage {
    Welcome { player_token: Uuid, session_id: Uuid, snapshot: OriginalFlowSnapshot },
    Resync { snapshot: OriginalFlowSnapshot },
    WorldUpdate { snapshot: OriginalFlowSnapshot },
    IntentResult { intent: String, accepted: bool, reason: Option<String>, snapshot: OriginalFlowSnapshot },
    BindingBlocked { intent: String, blockers: Vec<String>, snapshot: OriginalFlowSnapshot },
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClientEnvelope {
    pub version: u16,
    pub sequence: u64,
    pub session_id: Option<Uuid>,
    pub correlation_id: Uuid,
    pub payload: ClientCommand,
}

#[derive(Debug, Serialize)]
pub struct ServerEnvelope<'a> {
    pub version: u16,
    pub sequence: u64,
    pub session_id: Uuid,
    pub correlation_id: Option<Uuid>,
    pub payload: &'a ServerMessage,
}
