// Generated by tools/generate-protocol.mjs. Do not edit directly.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::{farm_validation::FarmReport, BottomMenuIntent, OriginalFlowSnapshot, WorldProjection};

pub const PROTOCOL_VERSION: u16 = 32;
pub const MAX_MESSAGE_BYTES: usize = 4194304;

#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case", deny_unknown_fields)]
pub enum ClientCommand {
    SubmitFarmReport { report: FarmReport },
    StartBuildingService { instance_id: String, hunter_id: u32, product_id: String },
    StartInfirmaryTreatment { instance_id: String, hunter_id: u32, product_id: String },
    CompleteBoot,
    SelectBottomMenu { menu: BottomMenuIntent },
    NavigateBack,
    EnterField,
    EnterMonsterMap { map_id: String },
    SetMonsterDensity { level: u8 },
    SetMonsterRegionDensity { region_id: String, level: u8 },
    SelectMonsterTarget { monster_id: String, hunter_id: u32 },
    SelectEntity { entity_id: String },
    ConstructBuilding { building_id: String },
    ConstructBuildingAt { building_id: String, grid_x: i32, grid_y: i32 },
    UpgradeBuilding { instance_id: String },
    MoveBuilding { instance_id: String, grid_x: i32, grid_y: i32 },
    UseBuilding { instance_id: String },
    SetMaterialRequest { instance_id: String, material_id: String, quantity: u32 },
    CancelMaterialRequest { instance_id: String, material_id: String },
    CraftShopItem { instance_id: String, recipe_id: String, material_id: Option<String>, quantity: u32 },
    OpenHunterProgression { hunter_id: u32 },
    AssignHunterHunt { hunter_id: u32, zone_id: String },
    ReturnHunterHunt { hunter_id: u32 },
    SellHunterLoot { hunter_id: u32 },
    ReviveHunter { hunter_id: u32 },
    LearnHunterSkill { hunter_id: u32, skill_id: String },
    UseHunterSkill { hunter_id: u32, skill_id: String, target_entity_id: Option<String> },
    BanishHunter { hunter_id: u32 },
    EquipHunterItem { hunter_id: u32, item_id: u32 },
    EquipHunterWeapon { hunter_id: u32, gear_instance_id: Uuid },
    StartHunterEnhancement { hunter_id: u32 },
    EnhanceHunterGear { hunter_id: u32, gear_instance_id: Uuid, mode: String, optional_material_ids: Vec<String> },
    ClaimQuestReward { quest_id: String },
    OpenShop { shop_id: String },
    PurchaseShopItem { hunter_id: u32, shop_id: String, product_id: String },
    SellShopItem { shop_id: String, product_id: String },
    ClaimMail { mail_id: String },
    ClaimRewardedAd { placement: String },
    StartTopupPurchase { product_id: String },
    RequestResync,
}

#[derive(Debug, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMessage {
    FarmReportQueued { window_id: u64 },
    Welcome { player_token: Uuid, session_id: Uuid, snapshot: OriginalFlowSnapshot },
    Resync { snapshot: OriginalFlowSnapshot },
    WorldUpdate { snapshot: OriginalFlowSnapshot },
    WorldFrame { world: WorldProjection },
    IntentResult { intent: String, accepted: bool, reason: Option<String>, snapshot: OriginalFlowSnapshot },
    BindingBlocked { intent: String, blockers: Vec<String>, snapshot: OriginalFlowSnapshot },
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClientEnvelope {
    pub version: u16,
    pub sequence: u64,
    pub session_id: Option<Uuid>,
    pub correlation_id: Uuid,
    pub payload: ClientCommand,
}

#[derive(Debug, Serialize)]
pub struct ServerEnvelope<'a> {
    pub version: u16,
    pub sequence: u64,
    pub session_id: Uuid,
    pub correlation_id: Option<Uuid>,
    pub payload: &'a ServerMessage,
}
