server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /game-assets/ {
    alias /game-assets/;
    access_log off;
    expires 30d;
    add_header Cache-Control "public, immutable";
  }
}
