import type { BottomMenuIntent } from "../generated/protocol";
import { originalUiLabel } from "../content/original-ui-labels";
import { t, type MessageKey } from "../i18n";
import { installShellViewportController } from "../ui/viewport-controller";

export type MenuAction = BottomMenuIntent | "field";

const menuItems: Array<{ action: MenuAction; label: MessageKey; icon: string; enabled: boolean }> = [
  { action: "build", label: "menu.build", icon: "sprites/menu_ic_01__6756.png", enabled: true },
  { action: "field", label: "menu.field", icon: "sprites/menu_ic_02__2060.png", enabled: true },
  { action: "character", label: "menu.hunters", icon: "sprites/menu_ic_03__6410.png", enabled: true },
  { action: "archive", label: "menu.storage", icon: "sprites/menu_ic_04__5070.png", enabled: false },
  { action: "store", label: "menu.shop", icon: "sprites/menu_ic_05__6398.png", enabled: true },
];

export const originalAsset = (sourcePath: string): string =>
  `/content/releases/original-flow-v1/${sourcePath}`;

export function mountGameShell(mount: HTMLDivElement): HTMLElement {
  mount.innerHTML = `
    <main class="game-shell entry-login">
      <section id="login-screen" class="login-screen" aria-label="${t("login.aria")}">
        <section class="basic-login-card">
          <span class="basic-login-brand">${t("app.brand")}</span><h1>${t("login.title")}</h1><p>${t("login.subtitle")}</p>
          <label for="login-email">${t("login.email")}</label><input id="login-email" type="email" maxlength="120" autocomplete="email" required />
          <label for="login-password">${t("login.password")}</label><input id="login-password" type="password" maxlength="128" autocomplete="current-password" required />
          <label for="demo-account-select">${t("login.demo_accounts")}</label><select id="demo-account-select"><option value="">${t("login.demo_choose")}</option><option value="demo1@evil.local">Hunter Lab Demo 1</option><option value="demo2@evil.local">Hunter Lab Demo 2</option><option value="demo3@evil.local">Hunter Lab Demo 3</option></select>
          <button id="enter-village" class="enter-village" type="button">${t("login.sign_in")}</button>
          <button id="register-account-toggle" class="basic-login-link" type="button">${t("login.register_profile")}</button>
          <form id="register-account-form" class="register-account-form" hidden>
            <label for="register-account-name">${t("login.display_name")}</label><input id="register-account-name" maxlength="24" autocomplete="nickname" required />
            <label for="register-account-email">${t("login.email")}</label><input id="register-account-email" type="email" maxlength="120" autocomplete="email" required />
            <label for="register-account-password">${t("login.password")}</label><input id="register-account-password" type="password" minlength="8" maxlength="128" autocomplete="new-password" required />
            <div class="boot-auth-actions"><button id="register-account-submit" class="boot-primary-button" type="submit">${t("login.create_profile")}</button><button id="register-account-cancel" class="boot-secondary-button" type="button">${t("common.cancel")}</button></div>
          </form>
          <small class="boot-account-note">${t("login.synced_account_note")}</small>
          <div class="login-readiness" hidden aria-live="polite"><i id="map-loading-fill"></i><span id="map-loading-label">${t("login.waiting_to_load")}</span></div>
        </section>
        <span id="boot-status" class="boot-status" role="status">${t("login.ready")}</span>
      </section>
      <section id="game-loading-screen" class="game-loading-screen" hidden aria-live="polite" aria-label="${t("loading.aria")}">
        <div class="game-loading-content"><span class="game-loading-kicker">${t("app.brand")}</span><h1>${t("loading.title")}</h1><p id="game-loading-status">${t("loading.sync_profile")}</p><div class="game-loading-track"><i id="game-loading-fill"></i></div><b id="game-loading-percent">0%</b><button id="game-loading-retry" type="button" hidden>${t("loading.reload")}</button></div>
      </section>
      <section id="village-screen" class="village-screen" aria-label="${t("world.village")}" aria-hidden="true">
        <div id="world-viewport" class="village-world" aria-label="${t("world.entity_world")}"></div><div id="hunter-enhancement-interactions" class="hunter-enhancement-interactions" aria-label="${t("world.enhancement_interactions")}"></div>
        <header class="resource-bar" aria-label="${t("world.resources")}"><div class="difficulty-hud"><img data-game-src="${originalAsset("sprites/top_mon_level_01__1480.png")}" alt="${t("world.easy_difficulty")}" /><b id="world-mode-label">${t("world.easy")}</b></div><div class="resource-ledger"><div class="resource-line"><img data-game-src="${originalAsset("sprites/top_ic_01_gold_24__4677.png")}" alt="${t("world.gold")}" /><b id="gold-amount">0</b></div><div class="resource-line unresolved"><img data-game-src="${originalAsset("sprites/top_ic_02_gem_24__4214.png")}" alt="${t("world.gem")}" /><b>--</b></div><div class="resource-line unresolved"><img data-game-src="${originalAsset("sprites/top_ic_03_element_24__1412.png")}" alt="${t("world.elemental")}" /><b>--</b></div><div class="resource-line unresolved"><img data-game-src="${originalAsset("sprites/top_ic_04_book_24__3078.png")}" alt="${t("world.book")}" /><b>--</b></div></div></header>
        <nav class="top-quick-actions" aria-label="${t("world.shortcuts")}"><button type="button" disabled title="${t("world.book_unavailable")}"><img data-game-src="${originalAsset("sprites/top_ic_book__3217.png")}" alt="${t("world.book")}" /></button><button type="button" disabled title="${t("world.rank_unavailable")}"><img data-game-src="${originalAsset("sprites/top_ic_rank__5074.png")}" alt="${t("world.rank")}" /></button><button type="button" data-action="character" title="${t("world.hunters")}"><img data-game-src="${originalAsset("sprites/top_ic_man__5368.png")}" alt="${t("world.hunters")}" /><b id="hunter-population">0/8</b></button><button type="button" data-action="build" title="${t("world.construct")}"><img data-game-src="${originalAsset("sprites/menu_ic_01__6756.png")}" alt="${t("world.construct")}" /></button><button type="button" disabled title="${t("world.settings_unavailable")}"><img data-game-src="${originalAsset("sprites/top_ic_setting__4198.png")}" alt="${t("world.settings")}" /></button></nav>
        <button class="quest-shortcut" type="button" disabled title="${t("world.quest_unavailable")}"><img data-game-src="${originalAsset("sprites/top_ic_quest__4944.png")}" alt="${t("world.quests")}" /></button><button id="field-back" class="field-back" type="button">${t("world.return_village")}</button>
        <aside id="evidence-diagnostics" class="evidence-diagnostics" aria-live="polite" hidden><b></b><span></span></aside>
        <section id="combat-hud" class="combat-hud" aria-label="${t("combat.aria")}" hidden><header><b>${t("combat.title")}</b><span id="combat-evidence"></span></header><div class="combatant"><span>${t("combat.hunter", { id: 1 })} · <i id="hunter-state"></i> · <i id="hunter-position"></i></span><div class="hp-track"><i id="hunter-hp-fill"></i></div><small id="hunter-hp"></small></div><div class="combatant"><span>${t("combat.monster", { id: 1001 })} · <i id="monster-state"></i> · <i id="monster-position"></i></span><div class="hp-track monster"><i id="monster-hp-fill"></i></div><small id="monster-hp"></small></div><div class="combat-ledger"><span id="combat-gold"></span><span id="combat-inventory"></span><span id="combat-drops"></span></div><button id="equip-fixture-item" type="button">${t("combat.equip_item", { id: 2001 })}</button></section>
        <div id="panel-message" class="panel-message" aria-live="polite" hidden><b></b><span></span></div>
        <section id="building-panel" class="building-panel source-popup" hidden aria-label="${t("building.aria")}"><button id="building-panel-close" class="source-red-button" type="button">${t("common.close")}</button><b id="building-name">${t("building.default_name")}</b><div class="building-source-header"><img id="building-preview" alt="" hidden /><div><span id="building-level"></span><small id="building-feature"></small><small id="building-condition"></small></div></div><div id="building-level-contract" class="building-level-contract"></div><div id="building-catalog" class="building-catalog"></div><div class="building-actions"><button id="building-construct" class="source-green-button" type="button" disabled>${t("building.construct")}</button><button id="building-upgrade" class="source-green-button" type="button" disabled>${t("common.upgrade")}</button><button id="building-use" class="source-green-button" type="button" disabled>${t("common.open")}</button><button id="building-sell" type="button" hidden>${t("common.sell")}</button></div></section>
        <section id="bounty-quest-pop" class="bounty-quest-pop source-popup" hidden aria-label="${t("bounty.popup_aria")}"><button id="bounty-close" class="source-red-button" type="button">${t("common.close")}</button><b id="bounty-title">${t("common.level_short", { level: 1 })} ${t("bounty.title")}</b><i class="source-popup-line"></i><p class="bounty-description">${t("bounty.description")}</p><div id="bounty-tier-tabs" class="bounty-tier-tabs"></div><div id="bounty-quest-list" class="bounty-quest-list"><p class="bounty-unresolved">${t("bounty.rows_unavailable")}</p></div><div class="bounty-upgrade-hint">${t("bounty.upgrade_hint")}<br /><em>${originalUiLabel("buildpop_9", "vi", [5])}</em></div><div class="source-popup-actions"><button id="bounty-upgrade" class="source-green-button" type="button">${t("common.upgrade")}</button><button id="bounty-close-bottom" class="source-red-button" type="button">${t("common.close")}</button></div></section>
        <section id="gear-create-pop" class="gear-create-pop source-popup" hidden aria-label="${t("craft.gear_popup_aria")}"><b id="gear-create-title">${t("craft.gear_create")}</b><i class="source-popup-line"></i><div class="gear-create-product"><div class="gear-frame"><img id="gear-create-icon" alt="" /><i aria-hidden="true"></i><output id="gear-frame-quantity">1</output></div><div class="gear-product-side"><div class="gear-create-meta"><strong id="gear-create-name"></strong><span id="gear-create-price"></span></div><div id="gear-quantity-row" class="gear-quantity-controls"><div class="quantity-stepper"><button id="gear-quantity-minus" class="gear-round-button minus" type="button" aria-label="${t("craft.decrease_quantity")}"></button><input id="gear-create-quantity" type="number" min="1" max="1000" step="1" inputmode="numeric" pattern="[0-9]*" value="1" aria-label="${t("craft.production_quantity")}" /><button id="gear-quantity-plus" class="gear-round-button plus" type="button" aria-label="${t("craft.increase_quantity")}"></button></div><div class="quantity-step-buttons"><button type="button" data-gear-delta="1">+1</button><button type="button" data-gear-delta="10">+10</button><button type="button" data-gear-delta="100">+100</button><button type="button" data-gear-delta="1000">+1000</button></div></div></div></div><div id="gear-create-description" class="gear-create-description"><button id="gear-lock" type="button" disabled>${t("common.lock")}</button></div><h3 id="gear-material-title">${t("craft.required_materials")}</h3><div id="gear-material-costs" class="gear-material-costs"></div><div class="source-popup-actions"><button id="gear-create-submit" class="source-green-button" type="button">${t("common.create")}</button><button id="gear-create-sell" class="source-green-button" type="button">${t("common.dismantle")}</button><button id="gear-create-close" class="source-red-button" type="button">${t("common.close")}</button></div></section>
        <section id="consum-create-pop" class="consum-create-pop source-popup" hidden aria-label="${t("craft.consumable_popup_aria")}"><b id="consum-create-title">${t("craft.quantity_title")}</b><i class="source-popup-line"></i><div class="consum-quantity-panel"><div class="consum-product-frame"><img id="consum-create-icon" alt="" /><span id="consum-create-icon-placeholder" class="product-icon-unresolved" aria-label="${t("craft.product_image_unavailable")}">?</span><output id="consum-create-quantity">1</output></div><div class="consum-quantity-controls"><span>${t("common.quantity")}</span><div class="quantity-stepper"><button id="consum-minus" class="consum-round-button minus" type="button" aria-label="${t("craft.decrease_quantity")}"></button><input id="consum-create-quantity-input" type="number" min="1" max="1000" step="1" inputmode="numeric" pattern="[0-9]*" value="1" aria-label="${t("craft.production_quantity")}" /><button id="consum-plus" class="consum-round-button plus" type="button" aria-label="${t("craft.increase_quantity")}"></button></div><div class="quantity-step-buttons"><button type="button" data-consum-delta="1">+1</button><button type="button" data-consum-delta="10">+10</button><button type="button" data-consum-delta="100">+100</button><button type="button" data-consum-delta="1000">+1000</button></div></div><p id="consum-conversion"></p></div><h3 id="consum-material-title">${t("craft.select_material")}</h3><div id="consum-material-grid" class="consum-material-grid"></div><div class="source-popup-actions"><button id="consum-create-submit" class="source-green-button" type="button">${t("common.produce")}</button><button id="consum-create-close" class="source-red-button" type="button">${t("common.close")}</button></div></section>
        <section id="trading-request-pop" class="trading-request-pop source-popup" hidden aria-label="${t("trading.request_editor_aria")}"><b>${t("trading.request_title")}</b><i class="source-popup-line"></i><div id="trading-request-content"></div></section>
        <button id="connection-status" class="connection-status connecting" type="button" aria-label="${t("world.server_status")}"><i></i><span>${t("world.connecting")}</span></button><span id="fps-counter" class="fps-counter" aria-live="off">FPS --</span>
      </section>
      <section id="roster-screen" class="roster-screen" aria-label="${t("roster.aria")}" aria-hidden="true"><img class="roster-background" data-game-src="/content/releases/visible-world-v1/maps/map_new01.png" alt="" /><section class="hunter-roster-panel bottom-menu-panel" aria-label="${t("roster.management")}"><header class="hunter-roster-header"><div class="hunter-roster-heading"><b>${t("roster.title")}</b></div><button id="roster-back" class="source-red-button" type="button" aria-label="${t("roster.close_aria")}">${t("common.close")}</button></header><div class="hunter-roster-body"><div id="hunter-active-list" class="hunter-card-grid"></div></div><footer id="hunter-roster-status" class="hunter-roster-status"></footer></section></section>
      <nav id="bottom-menu" class="bottom-menu persistent-bottom-menu" aria-label="${t("menu.aria")}" hidden>${menuItems.map((item) => `<button class="menu-button" type="button" data-action="${item.action}" ${item.enabled ? "" : `disabled title="${t("common.feature_in_development")}"`}><span class="menu-icon"><img data-game-src="${originalAsset(item.icon)}" alt="" /></span><b>${t(item.label)}</b></button>`).join("")}</nav>
      <div id="loading-transition" class="loading-transition" hidden><img data-game-src="${originalAsset("sprites/cloud_loading_btn__4266.png")}" alt="" /><span>${t("loading.loading")}</span></div>
      <section class="mobile-orientation-error" role="alert" aria-live="assertive"><div><b>${t("orientation.mobile_landscape_title")}</b><span>${t("orientation.mobile_landscape_body")}</span></div></section>
    </main>`;

  const shell = mount.querySelector<HTMLElement>(".game-shell");
  if (!shell) throw new Error(t("error.missing_shell"));
  installShellViewportController(shell);
  return shell;
}
