-- Generated from reverse-engineering/evidence/hunter-info-tables-v1.json.
-- Player-owned values remain nullable until recovered or explicitly written by gameplay.
INSERT INTO hunter_content_release(release_id, game_version, status, evidence_note)
VALUES ('evil-hunter-1.411.hunter-info-v1', '1.411', 'confirmed', 'Exact QuickSheet Hunter info definitions; player ownership and allocations are separate state.')
ON CONFLICT (release_id) DO NOTHING;

INSERT INTO hunter_class_definition
    (release_id, class_id, display_name, source_job_index, visual_family, evidence_confidence, semantics_status)
SELECT 'evil-hunter-1.411.hunter-info-v1', class_id, CASE WHEN source_job_index = 4 THEN 'DarkKnight' ELSE display_name END,
       source_job_index, visual_family, 'confirmed', 'resolved'
FROM hunter_class_definition WHERE release_id = 'migration.hunter-demo-v1'
ON CONFLICT (release_id, class_id) DO NOTHING;

UPDATE hunter_class_definition SET display_name = 'DarkKnight'
WHERE release_id = 'migration.hunter-demo-v1' AND source_job_index = 4;

ALTER TABLE hunter_skill_definition
    ADD COLUMN source_kind TEXT CHECK (source_kind IN ('basic', 'class_change')),
    ADD COLUMN source_index INTEGER,
    ADD COLUMN description TEXT,
    ADD COLUMN detail_description TEXT,
    ADD COLUMN max_level SMALLINT CHECK (max_level IS NULL OR max_level > 0),
    ADD COLUMN sub_job SMALLINT,
    ADD COLUMN third_job SMALLINT,
    ADD COLUMN fourth_job SMALLINT,
    ADD COLUMN source_parameters JSONB;

CREATE UNIQUE INDEX hunter_skill_source_unique
    ON hunter_skill_definition(release_id, source_kind, source_index)
    WHERE source_kind IS NOT NULL AND source_index IS NOT NULL;

INSERT INTO hunter_skill_definition
    (release_id, skill_id, class_id, display_name, icon_path, animation_name, evidence_confidence, semantics_status,
     source_kind, source_index, description, detail_description, max_level, sub_job, third_job, fourth_job, source_parameters)
VALUES
    ('evil-hunter-1.411.hunter-info-v1', 'basic:0', 'h1', 'Fury', NULL, NULL, 'confirmed', 'resolved', 'basic', 0, 'Attacks quickly for a certain time and increases Attack Speed.', 'Attack Speed increases by <color=#46CCFF>keepValueTimes</color> for <color=#46CCFF>keepTImeSecs</color>, and normal attack''s damage increases by <color=#46CCFF>valueCount%</color>.', 10, NULL, NULL, NULL, '{"index":0,"job":0,"maxLevel":10,"coolTime":15,"keepTimeByLevel":[10,11,11,12,12,13,13,14,14,15,15,16,16],"keepValueByLevel":[238,256,274,292,310,328,346,364,382,400,418,436,454],"valueTimeByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"valueCountByLevel":[10,20,30,40,50,60,70,80,90,100,110,120,130],"studyLevel":[1,10,20,30,40,50,60,70,80,90],"studyMoney":[0,250,500,750,1500,2250,4500,6750,13500,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'basic:1', 'h1', 'War Cry', NULL, NULL, 'confirmed', 'resolved', 'basic', 1, 'Charge to enemy and Stun it.', 'For <color=#46CCFF>keepTImeSecs</color>, when attacking, Hunter charge towards enemy by <color=#46CCFF>keepValue%</color> chance, and stun enemy for <color=#46CCFF>valueTimeSecs</color>', 5, NULL, NULL, NULL, '{"index":1,"job":0,"maxLevel":5,"coolTime":16,"keepTimeByLevel":[7,7,7,7,7],"keepValueByLevel":[18,21,24,27,30],"valueTimeByLevel":[3,3,3,3,3],"valueCountByLevel":[0,0,0,0,0],"studyLevel":[1,20,40,60,80],"studyMoney":[0,750,2250,6750,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'basic:2', 'h2', 'Holy Light', NULL, NULL, 'confirmed', 'resolved', 'basic', 2, 'Hits and provokes nearby enemies with holy power.', 'AOE attack that inflicts <color=#46CCFF>keepValue%</color> DPS', 10, NULL, NULL, NULL, '{"index":2,"job":1,"maxLevel":10,"coolTime":8,"keepTimeByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"keepValueByLevel":[430,560,690,820,950,1080,1210,1340,1470,1600,1730,1860,1990],"valueTimeByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"valueCountByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"studyLevel":[1,10,20,30,40,50,60,70,80,90],"studyMoney":[0,250,500,750,1500,2250,4500,6750,13500,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'basic:3', 'h2', 'Barrier', NULL, NULL, 'confirmed', 'resolved', 'basic', 3, 'Defends against enemy attacks by summoning a barrier.', 'Increases DEF by <color=#46CCFF>keepValue%</color> for <color=#46CCFF>keepTIme secs</color>', 5, NULL, NULL, NULL, '{"index":3,"job":1,"maxLevel":5,"coolTime":16,"keepTimeByLevel":[7,7,7,7,7],"keepValueByLevel":[36,42,48,54,60],"valueTimeByLevel":[0,0,0,0,0],"valueCountByLevel":[0,0,0,0,0],"studyLevel":[1,20,40,60,80],"studyMoney":[0,750,2250,6750,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'basic:4', 'h3', 'Multishot', NULL, NULL, 'confirmed', 'resolved', 'basic', 4, 'Rapidly shoots multiple arrows.', 'Fires <color=#46CCFF>valueCount times</color> and inflicts DPS x<color=#46CCFF>keepValue%</color> damage', 10, NULL, NULL, NULL, '{"index":4,"job":2,"maxLevel":10,"coolTime":6,"keepTimeByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"keepValueByLevel":[143,140,138,137,136,136,135,135,134,134,133,133,132],"valueTimeByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"valueCountByLevel":[4,5,6,7,8,9,10,11,12,13,14,15,16],"studyLevel":[1,10,20,30,40,50,60,70,80,90],"studyMoney":[0,250,500,750,1500,2250,4500,6750,13500,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'basic:5', 'h3', 'Dodge', NULL, NULL, 'confirmed', 'resolved', 'basic', 5, 'Increases Evasion for a certain time.', 'Increases evasion by <color=#46CCFF>keepValue%</color> for <color=#46CCFF>keepTIme secs</color>', 5, NULL, NULL, NULL, '{"index":5,"job":2,"maxLevel":5,"coolTime":16,"keepTimeByLevel":[7,7,7,7,7],"keepValueByLevel":[20,23,26,29,32],"valueTimeByLevel":[0,0,0,0,0],"valueCountByLevel":[0,0,0,0,0],"studyLevel":[1,20,40,60,80],"studyMoney":[0,750,2250,6750,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'basic:6', 'h4', 'Thunderbolt', NULL, NULL, 'confirmed', 'resolved', 'basic', 6, 'Lightning inflicts damage to nearby enemies.', 'AOE attack that inflicts <color=#46CCFF>keepValue%</color> DPS <color=#46CCFF>valueCount time(s)</color>', 10, NULL, NULL, NULL, '{"index":6,"job":3,"maxLevel":10,"coolTime":6,"keepTimeByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"keepValueByLevel":[300,400,250,300,234,267,225,250,220,240,217,234,215],"valueTimeByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"valueCountByLevel":[1,1,2,2,3,3,4,4,5,5,6,6,7],"studyLevel":[1,10,20,30,40,50,60,70,80,90],"studyMoney":[0,250,500,750,1500,2250,4500,6750,13500,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'basic:7', 'h4', 'Ice Armor', NULL, NULL, 'confirmed', 'resolved', 'basic', 7, 'Enemy who attacked hunter will lose ATK SPD.', 'For <color=#46CCFF>keepTImeSecs</color> when Hunter is attacked, Enemy''s ATK Speed decreases for <color=#46CCFF>valueTimeSecs</color> by <color=#46CCFF>keepValue%</color>.', 5, NULL, NULL, NULL, '{"index":7,"job":3,"maxLevel":5,"coolTime":16,"keepTimeByLevel":[7,7,7,7,7],"keepValueByLevel":[30,35,40,45,50],"valueTimeByLevel":[5,5,5,5,5],"valueCountByLevel":[0,0,0,0,0],"studyLevel":[1,20,40,60,80],"studyMoney":[0,750,2250,6750,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'basic:8', 'h5', 'Round Slash', NULL, NULL, 'confirmed', 'resolved', 'basic', 8, 'Swing the spear horizontally to release energy, dealing damage to enemies nearby.', 'Cast an AoE attack with damage equal to <color=#46CCFF>keepValue%</color> of the caster''s DPS', 10, NULL, NULL, NULL, '{"index":8,"job":4,"maxLevel":10,"coolTime":6,"keepTimeByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"keepValueByLevel":[300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500],"valueTimeByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"valueCountByLevel":[0,0,0,0,0,0,0,0,0,0,0,0,0],"studyLevel":[1,10,20,30,40,50,60,70,80,90],"studyMoney":[0,250,500,750,1500,2250,4500,6750,13500,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'basic:9', 'h5', 'Concentrate', NULL, NULL, 'confirmed', 'resolved', 'basic', 9, 'Concentrate to increase the chance of dealing a critical strike to the enemy.', 'The caster''s critical hit chance increases by <color=#46CCFF>keepValue%</color> for <color=#46CCFF>keepTIme sec</color>', 5, NULL, NULL, NULL, '{"index":9,"job":4,"maxLevel":5,"coolTime":16,"keepTimeByLevel":[7,7,7,7,7],"keepValueByLevel":[12,14,16,18,20],"valueTimeByLevel":[0,0,0,0,0],"valueCountByLevel":[0,0,0,0,0],"studyLevel":[1,20,40,60,80],"studyMoney":[0,750,2250,6750,20250],"subJob":null,"thirdJob":null,"fourthJob":null}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:100', 'h1', 'Dual Weapon', NULL, NULL, 'confirmed', 'resolved', 'class_change', 100, 'Can attack with Weapons on both hands.', 'Attack enemy with additional attack. Additional attack deals <color=#46CCFF>keepValue%</color> of current damage.', 30, 1, 0, 0, '{"index":100,"job":0,"subJob":1,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":30.700000762939453,"upKeepValue":1.7000000476837158,"secondValue":0,"upSecondValue":0,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:101', 'h1', 'Death Coil', NULL, NULL, 'confirmed', 'resolved', 'class_change', 101, 'After attacking an enemy, recover own HP.', 'Attacks enemy with <color=#46CCFF>keepValue%</color> of DPS that ignores dodge, and recovers own HP <color=#46CCFF>secondValue%</color> damage dealt.', 30, 2, 0, 0, '{"index":101,"job":0,"subJob":2,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":15,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":950,"upKeepValue":50,"secondValue":62,"upSecondValue":2,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:102', 'h2', 'Blessing', NULL, NULL, 'confirmed', 'resolved', 'class_change', 102, 'Heal own HP and becomes immune to status effect skills.', 'Recovers own HP by <color=#46CCFF>keepValue%</color> and becomes immune to status effect skills for <color=#46CCFF>keepTimeSecs</color> seconds', 30, 1, 0, 0, '{"index":102,"job":1,"subJob":1,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":3.0999999046325684,"upKeepTime":0.10000000149011612,"keepValue":6.199999809265137,"upKeepValue":0.20000000298023224,"secondValue":0,"upSecondValue":0,"valueTime":3.0999999046325684,"upValueTime":0.10000000149011612,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:103', 'h2', 'Silver Weapon', NULL, NULL, 'confirmed', 'resolved', 'class_change', 103, 'Gives Weapon Divine attribute, and enhance Holy Light.', 'Amplify own ATK by <color=#46CCFF>keepValue%</color>, and attack twice after using Holy Light (Additonal attack deals <color=#46CCFF>secondValue%</color> of ATK)', 30, 2, 0, 0, '{"index":103,"job":1,"subJob":2,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":9.699999809265137,"upKeepValue":0.699999988079071,"secondValue":25.200000762939453,"upSecondValue":1.2000000476837158,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:104', 'h3', 'Rain Fall', NULL, NULL, 'confirmed', 'resolved', 'class_change', 104, 'Attacks enemies within the range with Arrows falling from the sky.', 'Attacks enemies within the range with <color=#46CCFF>keepValue%</color> of DPS <color=#46CCFF>valueCountTimes</color> times', 30, 1, 0, 0, '{"index":104,"job":2,"subJob":1,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":176,"upKeepValue":6,"secondValue":0,"upSecondValue":0,"valueTime":0,"upValueTime":0,"valueCount":5,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:105', 'h3', 'Sniping', NULL, NULL, 'confirmed', 'resolved', 'class_change', 105, 'Attacks enemy with very powerful shot.', 'Attacks the enemy with damage equal to <color=#46CCFF>keepValue%</color> of the hunter''s DPS. The attack ignores the enemy''s evasion and stuns them for <color=#46CCFF>valueTime sec</color>.', 30, 2, 0, 0, '{"index":105,"job":2,"subJob":2,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":15,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":1055,"upKeepValue":55,"secondValue":0,"upSecondValue":0,"valueTime":2.5,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:106', 'h4', 'Blizzard', NULL, NULL, 'confirmed', 'resolved', 'class_change', 106, 'Attacks enemies within the range with Ice falling from the sky.', 'Attack enemies within the range with <color=#46CCFF>keepValue%</color> DPS <color=#46CCFF>valueCountTimes</color> times. Attacked enemies’ attack speed decreases by <color=#46CCFF> secondValue%</color> for <color=#46CCFF>valueTimeSecs</color> seconds', 30, 1, 0, 0, '{"index":106,"job":3,"subJob":1,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":247,"upKeepValue":7,"secondValue":50,"upSecondValue":0,"valueTime":3,"upValueTime":0,"valueCount":3,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:107', 'h4', 'Stone Curse', NULL, NULL, 'confirmed', 'resolved', 'class_change', 107, 'Attacks enemy and petrifies enemy for a moment.', 'Attacks the enemy with damage equal to <color=#46CCFF>keepValue%</color> of the hunter''s DPS. The attack ignores the enemy''s evasion and petrifies them for <color=#46CCFF>valueTime sec</color>.', 30, 2, 0, 0, '{"index":107,"job":3,"subJob":2,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":15,"upCoolTime":0,"keepTime":1,"upKeepTime":0,"keepValue":950,"upKeepValue":50,"secondValue":0,"upSecondValue":0,"valueTime":2.0799999237060547,"upValueTime":0.07999999821186066,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:108', 'h1', 'Battle Shout', NULL, NULL, 'confirmed', 'resolved', 'class_change', 108, 'Amplifies the ATK of nearby Allies with a shout.', 'ATK of nearby Allies is amplified by <color=#46CCFF>keepValue%</color> for <color=#46CCFF>keepTimeSec(s)</color>. (not duplicated)', 30, 1, 1, 0, '{"index":108,"job":0,"subJob":1,"thirdJob":1,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":10,"upKeepTime":0,"keepValue":13.399999618530273,"upKeepValue":0.4000000059604645,"secondValue":0,"upSecondValue":0,"valueTime":10,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:109', 'h1', 'Aura Blade', NULL, NULL, 'confirmed', 'resolved', 'class_change', 109, 'Attacks from a distance by giving one''s own weapon an aura.', 'Basic attack changes to a ranged attack and there''s a <color=#46CCFF>keepValue%</color> chance of attacking the enemy while ignoring the enemy''s DEF and Evasion.', 30, 2, 2, 0, '{"index":109,"job":0,"subJob":2,"thirdJob":2,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":15.199999809265137,"upKeepValue":1.2000000476837158,"secondValue":0,"upSecondValue":0,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:110', 'h2', 'Defensive Aura', NULL, NULL, 'confirmed', 'resolved', 'class_change', 110, 'Reduces damage received by nearby allies.', 'Reduces damage taken by nearby Allies by <color=#46CCFF>keepValue%</color> for <color=#46CCFF>keepTimeSec(s)</color> (not duplicated)', 30, 1, 1, 0, '{"index":110,"job":1,"subJob":1,"thirdJob":1,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":10,"upKeepTime":0,"keepValue":13.399999618530273,"upKeepValue":0.4000000059604645,"secondValue":0,"upSecondValue":0,"valueTime":10,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:111', 'h2', 'Hands of God', NULL, NULL, 'confirmed', 'resolved', 'class_change', 111, 'Summons the Hands of God to judge enemies.', '<color=#46CCFF>keepValue%</color> chance of ignoring the enemy''s defense and evasion and attacking nearby enemies every <color=#46CCFF>valueTime</color> seconds with damage equal to <color=#46CCFF>secondValueTimes</color> their ATK per second.', 30, 2, 2, 0, '{"index":111,"job":1,"subJob":2,"thirdJob":2,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":12.300000190734863,"upKeepValue":1.2999999523162842,"secondValue":2.5,"upSecondValue":0,"valueTime":2,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:112', 'h3', 'Song of Peace', NULL, NULL, 'confirmed', 'resolved', 'class_change', 112, 'Helps nearby Allies recover by playing sweet music.', 'Recovers the HP, Satiety and Mood of nearby allies by <color=#46CCFF>keepValue%</color> every <color=#46CCFF>valueTime</color> seconds (not duplicated).', 30, 1, 1, 0, '{"index":112,"job":2,"subJob":1,"thirdJob":1,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":1.649999976158142,"upKeepValue":0.15000000596046448,"secondValue":0,"upSecondValue":0,"valueTime":5,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:113', 'h3', 'Poison Bomb', NULL, NULL, 'confirmed', 'resolved', 'class_change', 113, 'Throw a poison gas grenade to poison and confuse enemies.', 'Attacks all enemies within the range with <color=#46CCFF>secondValue%</color> of DPS every <color=#46CCFF>0.5secs</color> during <color=#46CCFF>valueTimeSecs</color> while ignoring the enemies'' Evasion and DEF. The Evasion of the enemies is lowered by <color=#46CCFF>keepValue%</color>. (not duplicated).', 30, 2, 2, 0, '{"index":113,"job":2,"subJob":2,"thirdJob":2,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":10.5,"upKeepValue":0.5,"secondValue":84,"upSecondValue":4,"valueTime":7,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:114', 'h4', 'Summon Familiar', NULL, NULL, 'confirmed', 'resolved', 'class_change', 114, 'Summons a familiar to imitate the skills used by the owner.', 'When using Thunderbolt, Blizzard, Meteor, or Stone Curse, the familiar has a <color=#46CCFF>keepValue%</color> chance to recast the skill, and the recast skill will deal <color=#46CCFF>secondValue%</color> damage equal to the existing skill''s damage.', 30, 1, 1, 0, '{"index":114,"job":3,"subJob":1,"thirdJob":1,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":100,"upKeepValue":0,"secondValue":36.5,"upSecondValue":1.5,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:115', 'h4', 'Polymorph', NULL, NULL, 'confirmed', 'resolved', 'class_change', 115, 'Transforms into the Dark Lord and destroys enemies.', 'The basic attack is changed to a close range attack, the Ice Armor duration is doubled and the ATK of nearby enemies is reduced by <color=#46CCFF>keepValue%</color>.', 30, 2, 2, 0, '{"index":115,"job":3,"subJob":2,"thirdJob":2,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":13.399999618530273,"upKeepValue":0.4000000059604645,"secondValue":0,"upSecondValue":0,"valueTime":0.800000011920929,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:116', 'h1', 'Pulverizer', NULL, NULL, 'confirmed', 'resolved', 'class_change', 116, 'Occasionally, the sword emits a shockwave that will deal damage to the target and nearby enemies.', 'During a basic attack, there is <color=#46CCFF>keepValue%</color> chance of ignoring DEF and attacking enemies in wide-range, dealing as much damage as <color=#46CCFF>secondValue%</color> of DPS.', 30, 3, 0, 0, '{"index":116,"job":0,"subJob":3,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":15.5,"upKeepValue":0.5,"secondValue":42,"upSecondValue":2,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:117', 'h2', 'Dark Weapon', NULL, NULL, 'confirmed', 'resolved', 'class_change', 117, 'Gives the dark attribute to weapons and changes Holy Light.', 'Amplify own ATK by <color=#46CCFF>keepValue%</color> and, when Holy Light is used, instead of a provoking effect, all damage taken by the target is increased by <color=#46CCFF>secondValue%</color> for <color=#46CCFF>valueTime secs</color>.', 30, 3, 0, 0, '{"index":117,"job":1,"subJob":3,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":9.699999809265137,"upKeepValue":0.699999988079071,"secondValue":3.299999952316284,"upSecondValue":0.30000001192092896,"valueTime":4,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:118', 'h3', 'Summon Phoenix', NULL, NULL, 'confirmed', 'resolved', 'class_change', 118, 'Summons the Phoenix to participate in the battle.', 'When attacking, there is a <color=#46CCFF>35%</color> chance of attacking the enemy by dealing as much damage as <color=#46CCFF>keepValue%</color> of DPS, and all damage taken by the enemy increases by <color=#46CCFF>secondValue%</color> for <color=#46CCFF>valueTime secs</color> (cannot be activated for <color=#46CCFF>keepTime secs</color> after attacking.)', 30, 3, 0, 0, '{"index":118,"job":2,"subJob":3,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":2,"upKeepTime":0,"keepValue":210,"upKeepValue":10,"secondValue":3.4000000953674316,"upSecondValue":0.4000000059604645,"valueTime":3,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:119', 'h4', 'Meteor', NULL, NULL, 'confirmed', 'resolved', 'class_change', 119, 'Summons a massive meteor from the sky to attack.', 'Wide area attack by dealing as much damage as <color=#46CCFF>keepValue%</color> of DPS.', 30, 3, 0, 0, '{"index":119,"job":3,"subJob":3,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":1017,"upKeepValue":27,"secondValue":0,"upSecondValue":0,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:120', 'h1', 'Cyclone', NULL, NULL, 'confirmed', 'resolved', 'class_change', 120, 'Rotates at high speed to attack nearby enemies while holding a weapon.', 'For <color=#46CCFF>keepTime secs</color>, deals as much damage as <color=#46CCFF>keepValue%</color> of own DPS, ignoring the enemy''s DEF and attacks every <color=#46CCFF>valueTime secs</color>. Reduces damage taken while casting by <color=#46CCFF>secondValue%</color>.', 30, 3, 3, 0, '{"index":120,"job":0,"subJob":3,"thirdJob":3,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":3,"upKeepTime":0,"keepValue":134,"upKeepValue":4,"secondValue":40,"upSecondValue":0,"valueTime":0.25,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:121', 'h2', 'Execution', NULL, NULL, 'confirmed', 'resolved', 'class_change', 121, 'Unleashes the power of Darkness to strengthen oneself.', 'For <color=#46CCFF>keepTime secs</color>, the damage taken is reduced by <color=#46CCFF>25%</color> and ATK is amplified by <color=#46CCFF>keepValue%</color>. When attacking, there is a <color=#46CCFF>secondValue%</color> chance to ignore the enemy''s DEF and Evasion, and attack with as much damage as <color=#46CCFF>400%</color> of DPS.', 30, 3, 3, 0, '{"index":121,"job":1,"subJob":3,"thirdJob":3,"fourthJob":0,"maxLevel":30,"coolTime":30,"upCoolTime":0,"keepTime":10,"upKeepTime":0,"keepValue":42,"upKeepValue":2,"secondValue":20.5,"upSecondValue":0.5,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:122', 'h3', 'Mystic Arrow', NULL, NULL, 'confirmed', 'resolved', 'class_change', 122, 'Uses arrows with mysterious power to enhance attacks.', 'Amplify own ATK by <color=#46CCFF>keepValue%</color>, ignores enemy''s Evasion and DEF with a chance of <color=#46CCFF>secondValue%</color> (applies to basic attacks, multi-shot only).', 30, 3, 3, 0, '{"index":122,"job":2,"subJob":3,"thirdJob":3,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":15.199999809265137,"upKeepValue":1.2000000476837158,"secondValue":15.199999809265137,"upSecondValue":1.2000000476837158,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:123', 'h4', 'Nightmare', NULL, NULL, 'confirmed', 'resolved', 'class_change', 123, 'Summons a terrible nightmare, causing the target and nearby enemies to panic.', 'Wide area attack with as much damage as <color=#46CCFF>keepValue%</color> of DPS, and makes the target panic for <color=#46CCFF>valueTime secs</color>.', 30, 3, 3, 0, '{"index":123,"job":3,"subJob":3,"thirdJob":3,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":315,"upKeepValue":15,"secondValue":0,"upSecondValue":0,"valueTime":1.100000023841858,"upValueTime":0.10000000149011612,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:124', 'h1', 'Blade Finish', NULL, NULL, 'confirmed', 'resolved', 'class_change', 124, 'Summons a sword from the sky to attack enemies.', 'Deals a single hit with damage equal to <color=#46CCFF>keepValue%</color> of the caster''s DPS.
$(Skill ATK is deamplified by 60% in PvP)$', 10, 0, 0, 1, '{"index":124,"job":0,"subJob":0,"thirdJob":0,"fourthJob":1,"maxLevel":10,"coolTime":20,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":3500,"upKeepValue":500,"secondValue":0,"upSecondValue":0,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:125', 'h1', 'Commanding Shout', NULL, NULL, 'confirmed', 'resolved', 'class_change', 125, 'Lets out a shout to raise the spirits of allies.', 'Critical hit damage of nearby allies is increased by <color=#46CCFF>keepValue%</color> for <color=#46CCFF>keepTime sec</color>', 10, 0, 0, 2, '{"index":125,"job":0,"subJob":0,"thirdJob":0,"fourthJob":2,"maxLevel":10,"coolTime":30,"upCoolTime":0,"keepTime":30,"upKeepTime":0,"keepValue":13,"upKeepValue":3,"secondValue":0,"upSecondValue":0,"valueTime":30,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:126', 'h2', 'Token of Punishment', NULL, NULL, 'confirmed', 'resolved', 'class_change', 126, 'Creates the Token of Punishment to enhance the caster during normal attacks.', 'During normal attacks, there is a <color=#46CCFF>secondValue%</color> chance to obtain a Token of Punishment. The token lasts for <color=#46CCFF>keepTime sec</color> and each token amplifies the caster''s ATK by <color=#46CCFF>keepValue%</color>. Up to 5 Tokens of Punishment can be held.', 10, 0, 0, 1, '{"index":126,"job":1,"subJob":0,"thirdJob":0,"fourthJob":1,"maxLevel":10,"coolTime":30,"upCoolTime":0,"keepTime":30,"upKeepTime":0,"keepValue":2,"upKeepValue":0,"secondValue":16,"upSecondValue":1,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:127', 'h2', 'Light''s Grace', NULL, NULL, 'confirmed', 'resolved', 'class_change', 127, 'Protects allies nearby with Light''s Grace.', 'Allies nearby are protected with a shield that has <color=#46CCFF>keepValue%</color> of the ally''s max HP. The shield lasts up to <color=#46CCFF>keepTime sec</color>', 10, 0, 0, 2, '{"index":127,"job":1,"subJob":0,"thirdJob":0,"fourthJob":2,"maxLevel":10,"coolTime":30,"upCoolTime":0,"keepTime":5,"upKeepTime":0,"keepValue":6,"upKeepValue":1,"secondValue":0,"upSecondValue":0,"valueTime":5,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:128', 'h3', 'Vengeance', NULL, NULL, 'confirmed', 'resolved', 'class_change', 128, 'Transforms into the spirit of vengeance and uses special arrows.', 'For <color=#46CCFF>keepTime sec</color>, during normal attacks, there is a <color=#46CCFF>secondValue%</color> chance to cast Arrow of Vengeance. Arrow of Vengeance deals a single hit with damage equal to <color=#46CCFF>keepValue%</color> of the caster''s DPS
$(Skill ATK is deamplified by 60% in PvP)$', 10, 0, 0, 1, '{"index":128,"job":2,"subJob":0,"thirdJob":0,"fourthJob":1,"maxLevel":10,"coolTime":30,"upCoolTime":0,"keepTime":10,"upKeepTime":0,"keepValue":290,"upKeepValue":40,"secondValue":100,"upSecondValue":0,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:129', 'h3', 'Falling Star', NULL, NULL, 'confirmed', 'resolved', 'class_change', 129, 'Pours down stars from the sky to attack enemies.', 'Deals an AoE attack with damage equal to <color=#46CCFF>keepValue%</color> of the caster''s DPS every <color=#46CCFF>secondValue sec</color> for <color=#46CCFF>valueTime sec</color>
$(Skill ATK is deamplified by 60% in PvP)$', 10, 0, 0, 2, '{"index":129,"job":2,"subJob":0,"thirdJob":0,"fourthJob":2,"maxLevel":10,"coolTime":20,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":240,"upKeepValue":40,"secondValue":1,"upSecondValue":0,"valueTime":7,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:130', 'h4', 'Mana Charge', NULL, NULL, 'confirmed', 'resolved', 'class_change', 130, 'Gathers mana orbs to enhance skills.', 'When a hunter directly casts Thunderbolt, they obtain <color=#46CCFF>valueCount</color> mana orb(s). A mana orb lasts for <color=#46CCFF>keepTime sec</color>. Up to 5 mana orbs can be held. When casting an orb skill, <color=#46CCFF>secondValue</color> mana orb(s) are used to amplify the skill ATK by <color=#46CCFF>keepValue%</color>.
Orb skills: Blizzard, Stone Curse, Meteor, Nightmare
The Mana Charge effect also applies to orb skills cast by a Familiar.
$(Amplification is deamplified by 50% in PvP)$', 10, 0, 0, 1, '{"index":130,"job":3,"subJob":0,"thirdJob":0,"fourthJob":1,"maxLevel":10,"coolTime":0,"upCoolTime":0,"keepTime":30,"upKeepTime":0,"keepValue":14,"upKeepValue":4,"secondValue":1,"upSecondValue":0,"valueTime":0,"upValueTime":0,"valueCount":1,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:131', 'h4', 'Elemental Force', NULL, NULL, 'confirmed', 'resolved', 'class_change', 131, 'Uses the power of flame or ice to attack enemies during normal attacks.', 'During normal attacks, there is a <color=#46CCFF>valueCount%</color> chance to cast Elemental Force to either deal a single flame hit with damage equal to <color=#46CCFF>keepValue%</color> of the DPS, or deal an AoE ice attack with damage equal to <color=#46CCFF>secondValue%</color> of the DPS.
$(Skill ATK is deamplified by 60% in PvP)$', 10, 0, 0, 2, '{"index":131,"job":3,"subJob":0,"thirdJob":0,"fourthJob":2,"maxLevel":10,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":180,"upKeepValue":30,"secondValue":83,"upSecondValue":13,"valueTime":0,"upValueTime":0,"valueCount":25,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:132', 'h5', 'Equitation', NULL, NULL, 'confirmed', 'resolved', 'class_change', 132, 'Reaches the pinnacle of horsemanship, unleashing great power while mounted.', 'The damage taken is reduced by <color=#46CCFF>keepValue%</color>, and using Round Slash casts two attacks (additional attack deals <color=#46CCFF>secondValue%</color> damage). Equitation is only applied while mounted, and the dragon of the Dragon Knight also counts as a mount.', 30, 1, 0, 0, '{"index":132,"job":4,"subJob":1,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":8.399999618530273,"upKeepValue":0.4000000059604645,"secondValue":25.200000762939453,"upSecondValue":1.2000000476837158,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:133', 'h5', 'Shadow Strike', NULL, NULL, 'confirmed', 'resolved', 'class_change', 133, 'Imbues the spear with the power of shadows, driving it into the enemy''s body.', 'Ignore the enemy''s evasion and attack them with damage equal to <color=#46CCFF>keepValue%</color> of the hunter''s DPS and stun them for <color=#46CCFF>valueTime sec</color>. At the start of a PvP match, the Shadow Lancer will not be selected for the first targeting for <color=#46CCFF>keepTime sec</color>, and will teleport to the furthest enemy.', 30, 2, 0, 0, '{"index":133,"job":4,"subJob":2,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":15,"upCoolTime":0,"keepTime":1.5,"upKeepTime":0,"keepValue":1050,"upKeepValue":50,"secondValue":0,"upSecondValue":0,"valueTime":2.5,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:134', 'h5', 'Spin Splash', NULL, NULL, 'confirmed', 'resolved', 'class_change', 134, 'Has a chance to cast Spin Splash during normal attacks.', 'During normal attacks, Spin Splash is cast at a <color=#46CCFF>secondValue%</color> chance. For <color=#46CCFF>keepTime sec</color>, Spin Splash ignores the DEF and deals AoE attacks with damage equal to <color=#46CCFF>keepValue%</color> of the DPS every <color=#46CCFF>valueTime sec</color>. (Cannot be activated for <color=#46CCFF>2 sec</color> after casting)', 30, 3, 0, 0, '{"index":134,"job":4,"subJob":3,"thirdJob":0,"fourthJob":0,"maxLevel":30,"coolTime":0,"upCoolTime":0,"keepTime":2,"upKeepTime":0,"keepValue":22,"upKeepValue":2,"secondValue":25,"upSecondValue":0,"valueTime":0.4000000059604645,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":100000,"addStudySoul":220}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:135', 'h5', 'Piercing Thrust', NULL, NULL, 'confirmed', 'resolved', 'class_change', 135, 'Thrusts the spear deeply, piercing enemies and reinforcing defense with a shield.', 'Cast an AoE attack with damage equal to <color=#46CCFF>keepValue%</color> of the hunter''s DPS. The damage taken by the caster is reduced by <color=#46CCFF>secondValue%</color> for every enemy within range of the skill. (Stacks up to <color=#46CCFF>valueCount</color> times) The damage reduction effect lasts for <color=#46CCFF>keepTime sec</color>.', 30, 1, 1, 0, '{"index":135,"job":4,"subJob":1,"thirdJob":1,"fourthJob":0,"maxLevel":30,"coolTime":15,"upCoolTime":0,"keepTime":10,"upKeepTime":0,"keepValue":940,"upKeepValue":40,"secondValue":4.199999809265137,"upSecondValue":0.20000000298023224,"valueTime":0,"upValueTime":0,"valueCount":3,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:136', 'h5', 'Shade Javelin', NULL, NULL, 'confirmed', 'resolved', 'class_change', 136, 'Throws a spear imbued with the power of wraiths, instilling terror in the enemy.', 'Attacks the enemy with damage equal to <color=#46CCFF>keepValue%</color> of the hunter''s DPS. The attack ignores the enemy''s evasion and makes them panic for <color=#46CCFF>valueTime sec</color>.', 30, 2, 2, 0, '{"index":136,"job":4,"subJob":2,"thirdJob":2,"fourthJob":0,"maxLevel":30,"coolTime":15,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":970,"upKeepValue":70,"secondValue":0,"upSecondValue":0,"valueTime":1.100000023841858,"upValueTime":0.10000000149011612,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:137', 'h5', 'Dragon Breath', NULL, NULL, 'confirmed', 'resolved', 'class_change', 137, 'Unleashes a fiery breath from the mounted dragon''s mouth to burn enemies.', 'For <color=#46CCFF>keepTime sec</color>, deal AoE attacks with damage equal to <color=#46CCFF>keepValue%</color> of the hunter''s DPS every <color=#46CCFF>valueTime sec</color>. When casting Dragon Breath, become immune to status effects that limit actions.', 30, 3, 3, 0, '{"index":137,"job":4,"subJob":3,"thirdJob":3,"fourthJob":0,"maxLevel":30,"coolTime":20,"upCoolTime":0,"keepTime":2,"upKeepTime":0,"keepValue":207,"upKeepValue":17,"secondValue":0,"upSecondValue":0,"valueTime":0.4000000059604645,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":5,"addStudySoul":120}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:138', 'h5', 'Hyper Blitz', NULL, NULL, 'confirmed', 'resolved', 'class_change', 138, 'Has a chance to cast Hyper Blitz during normal attacks.', 'During normal attacks, there is a <color=#46CCFF>secondValue%</color> chance to cast <color=#46CCFF>valueCount</color> AoE attack(s) with damage equal to <color=#46CCFF>keepValue%</color> of the DPS. Hyper Blitz ignores the enemy''s DEF.
$(Skill ATK is deamplified by 60% in PvP)$', 10, 0, 0, 1, '{"index":138,"job":4,"subJob":0,"thirdJob":0,"fourthJob":1,"maxLevel":10,"coolTime":0,"upCoolTime":0,"keepTime":0,"upKeepTime":0,"keepValue":37,"upKeepValue":7,"secondValue":25,"upSecondValue":0,"valueTime":0,"upValueTime":0,"valueCount":5,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb),
    ('evil-hunter-1.411.hunter-info-v1', 'class_change:139', 'h5', 'Mistilteinn', NULL, NULL, 'confirmed', 'resolved', 'class_change', 139, 'Summons the cursed spear Mistilteinn to unleash a powerful curse.', 'Cast an AoE attack with damage equal to <color=#46CCFF>keepValue%</color> of the DPS. Create a cursed area for <color=#46CCFF>keepTime sec</color> that grants enemies within range a status effect that increases the damage taken from critical hits by <color=#46CCFF>secondValue%</color>.
$(Skill ATK is deamplified by 60% in PvP)$', 10, 0, 0, 2, '{"index":139,"job":4,"subJob":0,"thirdJob":0,"fourthJob":2,"maxLevel":10,"coolTime":20,"upCoolTime":0,"keepTime":7,"upKeepTime":0,"keepValue":700,"upKeepValue":200,"secondValue":6,"upSecondValue":1,"valueTime":0,"upValueTime":0,"valueCount":0,"upValueCount":0,"firstStudySoul":500,"addStudySoul":10}'::jsonb)
ON CONFLICT (release_id, skill_id) DO NOTHING;

CREATE TABLE hunter_characteristic_definition (
    release_id TEXT NOT NULL REFERENCES hunter_content_release(release_id) ON DELETE CASCADE,
    characteristic_id TEXT NOT NULL,
    source_index SMALLINT NOT NULL CHECK (source_index >= 0),
    display_name TEXT NOT NULL,
    description TEXT,
    effect_value DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (release_id, characteristic_id),
    UNIQUE (release_id, source_index)
);

INSERT INTO hunter_characteristic_definition
    (release_id, characteristic_id, source_index, display_name, description, effect_value)
VALUES
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:0', 0, 'Strong', NULL, 10),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:1', 1, 'Fast Runner', NULL, 10),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:2', 2, 'Swift', NULL, 10),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:3', 3, 'Fragile', NULL, 10),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:4', 4, 'Sluggish', NULL, 10),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:5', 5, 'Thickheaded', NULL, 10),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:6', 6, 'Careless', NULL, 20),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:7', 7, 'Stingy', NULL, 20),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:8', 8, 'Charismatic', NULL, 5),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:9', 9, 'Dead Weight', NULL, 5),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:10', 10, 'Baggy Eyes', NULL, 20),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:11', 11, 'Energetic', NULL, 20),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:12', 12, 'Overweight', NULL, 20),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:13', 13, 'Skinny', NULL, 20),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:14', 14, 'Optimistic', NULL, 20),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:15', 15, 'Pessimistic', NULL, 20),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:16', 16, 'Coward', NULL, 60),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:17', 17, 'Fearless', NULL, 0),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:18', 18, 'Addict', NULL, 0),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:19', 19, 'Scared of Hospital', NULL, 0),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:20', 20, 'Heroic', NULL, 7),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:21', 21, 'Rich', NULL, 120),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:22', 22, 'Gambler', NULL, 5),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:23', 23, 'Man of Steel', NULL, 10),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:24', 24, 'Nimble', NULL, 3),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:25', 25, 'Laggard', NULL, 3),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:26', 26, 'Sharp', NULL, 3),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:27', 27, 'Dull', NULL, 3),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:28', 28, 'Ordinary', NULL, 0),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:29', 29, 'YOLO', NULL, 0),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:30', 30, 'Internet Troll', NULL, 0),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:31', 31, 'Naughty', NULL, 0),
    ('evil-hunter-1.411.hunter-info-v1', 'characteristic:32', 32, 'Rude', NULL, 0);

CREATE TABLE hunter_growth_property_definition (
    release_id TEXT NOT NULL REFERENCES hunter_content_release(release_id) ON DELETE CASCADE,
    property_id TEXT NOT NULL,
    source_index SMALLINT NOT NULL CHECK (source_index BETWEEN 0 AND 14),
    display_name TEXT NOT NULL,
    description TEXT NOT NULL,
    value_per_rank DOUBLE PRECISION NOT NULL,
    icon_path TEXT NOT NULL,
    icon_binding_confidence TEXT NOT NULL CHECK (icon_binding_confidence IN ('confirmed', 'strongly_inferred')),
    PRIMARY KEY (release_id, property_id),
    UNIQUE (release_id, source_index)
);

INSERT INTO hunter_growth_property_definition
    (release_id, property_id, source_index, display_name, description, value_per_rank, icon_path, icon_binding_confidence)
VALUES
    ('evil-hunter-1.411.hunter-info-v1', 'growth:0', 0, 'Secret Technique of HP', '{0:f2}% Increase HP', 0.15000000596046448, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_00__5672.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:1', 1, 'Secret Technique of Mood', '{0:f2}% Increase Mood', 0.30000001192092896, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_01__6236.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:2', 2, 'Secret Technique of satiety', '{0:f2}% Increase satiety', 0.30000001192092896, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_02__2676.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:3', 3, 'Secret Technique of Deep Sleep', '{0:f2}% Increase Stamina', 0.30000001192092896, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_03__6357.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:4', 4, 'Secret Technique of Strength', '{0:f2}% Increase ATK', 0.15000000596046448, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_04__4308.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:5', 5, 'Secret Technique of Tanking', '{0:f2}% Increase DEF', 0.15000000596046448, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_05__4220.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:6', 6, 'Secret Technique of Lucky Punch', '{0:f2}% Increase CRIT', 0.10000000149011612, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_06__5960.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:7', 7, 'Secret Technique of Agility', '{0:f2}% Increase ATK SPD', 0.10000000149011612, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_07__2125.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:8', 8, 'Secret Technique of Evasion', '{0:f2}% Increase Evasion', 0.10000000149011612, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_08__1506.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:9', 9, 'Secret Technique of Walking', '{0:f2}% Increase Movement Speed', 0.15000000596046448, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_09__7392.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:10', 10, 'Secret Technique of Skill: {0}', '{0:f2}% Decrease Skill Cooltime', 0.10000000149011612, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_10__7011.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:11', 11, 'Secret Technique of Skill: {0}', '{0:f2}% Decrease Skill Cooltime', 0.10000000149011612, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_11__3254.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:12', 12, 'Secret Technique of Mood Control', '{0:f2}% Decrease Mood consumption', 0.30000001192092896, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_12__5120.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:13', 13, 'Secret Technique of Diet Control', '{0:f2}% Decrease satiety consumption', 0.30000001192092896, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_13__6059.png', 'strongly_inferred'),
    ('evil-hunter-1.411.hunter-info-v1', 'growth:14', 14, 'Secret Technique of Stamina Control', '{0:f2}% Decrease Stamina consumption', 0.30000001192092896, '/content/releases/evil-hunter-1.411/hunter-assets/ui/hunter-info-growth/growth_ic_14__4190.png', 'strongly_inferred');

CREATE TABLE hunter_riding_pet_definition (
    release_id TEXT NOT NULL REFERENCES hunter_content_release(release_id) ON DELETE CASCADE,
    riding_pet_id TEXT NOT NULL, source_index SMALLINT NOT NULL, grade SMALLINT NOT NULL,
    background_type SMALLINT NOT NULL, display_name TEXT NOT NULL, content TEXT, icon_path TEXT,
    PRIMARY KEY (release_id, riding_pet_id), UNIQUE (release_id, source_index)
);

INSERT INTO hunter_riding_pet_definition
    (release_id, riding_pet_id, source_index, grade, background_type, display_name, content, icon_path)
VALUES
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:0', 0, 0, 0, '없음', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:1', 1, 2, 0, 'Leo', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:2', 2, 1, 0, 'Pyro', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:3', 3, 2, 0, 'Inferno', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:4', 4, 2, 0, 'Pinia', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:5', 5, 2, 1, 'Blubee', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:6', 6, 1, 1, 'Tucan', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:7', 7, 1, 0, 'Grizzly', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:8', 8, 1, 0, 'Gray', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:9', 9, 1, 1, 'Dun Dun', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:10', 10, 1, 0, 'Wang Wang', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:11', 11, 0, 1, 'Goose', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:12', 12, 0, 1, 'Pony', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:13', 13, 0, 1, 'Sommy', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:14', 14, 0, 1, 'Smoky', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:15', 15, 0, 1, 'Mashybara', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:16', 16, 0, 1, 'Toto', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:17', 17, 0, 0, 'Dotty', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:18', 18, 0, 0, 'Kiwi', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:19', 19, 0, 1, 'Seedshrew', NULL, NULL),
    ('evil-hunter-1.411.hunter-info-v1', 'riding-pet:20', 20, 0, 1, 'Daisy', NULL, NULL);

ALTER TABLE player_hunter
    ADD COLUMN characteristic_release_id TEXT,
    ADD COLUMN characteristic_id TEXT,
    ADD COLUMN xp_to_next_level BIGINT CHECK (xp_to_next_level IS NULL OR xp_to_next_level >= 0),
    ADD COLUMN dps_milli BIGINT CHECK (dps_milli IS NULL OR dps_milli >= 0),
    ADD COLUMN critical_rate_bps INTEGER CHECK (critical_rate_bps IS NULL OR critical_rate_bps >= 0),
    ADD COLUMN attack_speed_milli INTEGER CHECK (attack_speed_milli IS NULL OR attack_speed_milli >= 0),
    ADD COLUMN evasion_rate_bps INTEGER CHECK (evasion_rate_bps IS NULL OR evasion_rate_bps >= 0),
    ADD COLUMN awakening_current INTEGER CHECK (awakening_current IS NULL OR awakening_current >= 0),
    ADD COLUMN awakening_maximum INTEGER CHECK (awakening_maximum IS NULL OR awakening_maximum >= 0),
    ADD COLUMN reincarnation_current INTEGER CHECK (reincarnation_current IS NULL OR reincarnation_current >= 0),
    ADD COLUMN reincarnation_maximum INTEGER CHECK (reincarnation_maximum IS NULL OR reincarnation_maximum >= 0),
    ADD COLUMN is_locked BOOLEAN,
    ADD COLUMN secret_points INTEGER CHECK (secret_points IS NULL OR secret_points >= 0),
    ADD COLUMN riding_pet_state_resolved BOOLEAN NOT NULL DEFAULT FALSE,
    ADD CONSTRAINT player_hunter_characteristic_fk FOREIGN KEY (characteristic_release_id, characteristic_id)
        REFERENCES hunter_characteristic_definition(release_id, characteristic_id),
    ADD CONSTRAINT player_hunter_awaken_pair CHECK ((awakening_current IS NULL) = (awakening_maximum IS NULL)),
    ADD CONSTRAINT player_hunter_reincarnation_pair CHECK ((reincarnation_current IS NULL) = (reincarnation_maximum IS NULL));

CREATE TABLE player_hunter_growth (
    player_token UUID NOT NULL, hunter_id BIGINT NOT NULL, release_id TEXT NOT NULL, property_id TEXT NOT NULL,
    allocated_points INTEGER NOT NULL CHECK (allocated_points >= 0),
    PRIMARY KEY (player_token, hunter_id, property_id),
    FOREIGN KEY (player_token, hunter_id) REFERENCES player_hunter(player_token, hunter_id) ON DELETE CASCADE,
    FOREIGN KEY (release_id, property_id) REFERENCES hunter_growth_property_definition(release_id, property_id)
);

CREATE TABLE player_hunter_material_stack (
    player_token UUID NOT NULL, hunter_id BIGINT NOT NULL, economy_release_id TEXT NOT NULL, item_id TEXT NOT NULL,
    quantity BIGINT NOT NULL CHECK (quantity > 0), reserved_quantity BIGINT NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0 AND reserved_quantity <= quantity),
    PRIMARY KEY (player_token, hunter_id, economy_release_id, item_id),
    FOREIGN KEY (player_token, hunter_id) REFERENCES player_hunter(player_token, hunter_id) ON DELETE CASCADE,
    FOREIGN KEY (economy_release_id, item_id) REFERENCES economy_item_definition(release_id, item_id)
);

CREATE TABLE player_riding_pet (
    player_token UUID NOT NULL, riding_pet_instance_id UUID NOT NULL DEFAULT gen_random_uuid(), release_id TEXT NOT NULL, riding_pet_id TEXT NOT NULL,
    level INTEGER, grade INTEGER, PRIMARY KEY (player_token, riding_pet_instance_id),
    FOREIGN KEY (release_id, riding_pet_id) REFERENCES hunter_riding_pet_definition(release_id, riding_pet_id)
);

CREATE TABLE player_hunter_riding_pet (
    player_token UUID NOT NULL, hunter_id BIGINT NOT NULL, riding_pet_instance_id UUID NOT NULL,
    PRIMARY KEY (player_token, hunter_id), UNIQUE (player_token, riding_pet_instance_id),
    FOREIGN KEY (player_token, hunter_id) REFERENCES player_hunter(player_token, hunter_id) ON DELETE CASCADE,
    FOREIGN KEY (player_token, riding_pet_instance_id) REFERENCES player_riding_pet(player_token, riding_pet_instance_id) ON DELETE CASCADE
);

COMMENT ON COLUMN player_hunter.dps_milli IS 'Nullable authoritative snapshot; no original DPS formula has been recovered.';
COMMENT ON TABLE player_hunter_material_stack IS 'Per-Hunter carried material state; never projected from town stock.';
