#!/usr/bin/env python3
"""Generate a deterministic PostgreSQL bundle for static core-game catalogs."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RELEASE = ROOT / "packages/content/releases/evil-hunter-1.411"
OUT = ROOT / "infra/db/core_game/001_core_game_catalog.sql"


def sql_text(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def sql_json(value: object) -> str:
    return sql_text(json.dumps(value, ensure_ascii=False, separators=(",", ":"))) + "::jsonb"


def load(name: str) -> tuple[dict, str]:
    path = RELEASE / name
    raw = path.read_bytes()
    return json.loads(raw), hashlib.sha256(raw).hexdigest()


def main() -> None:
    monster, monster_sha = load("monster-runtime-catalog.json")
    market, market_sha = load("monster-material-market-catalog.json")
    gear, gear_sha = load("gear-catalog.json")
    experience, experience_sha = load("experience-runtime-catalog.json")

    lines = [
        "-- Generated by tools/generate-core-game-sql.py; do not hand-edit.",
        "-- Static catalog data only. Player state and transaction ledgers remain in migrations.",
        "CREATE SCHEMA IF NOT EXISTS core_game;",
        "DROP TABLE IF EXISTS core_game.unresolved_recipe_condition, core_game.building_material_cost, core_game.recipe_material_input, core_game.monster_material_drop, core_game.monster_unique_gear_pool, core_game.monster, core_game.experience, core_game.gear, core_game.material_market, core_game.catalog_source, core_game.catalog_release CASCADE;",
        "CREATE TABLE core_game.catalog_release (release_id TEXT PRIMARY KEY, game_version TEXT NOT NULL, status TEXT NOT NULL, catalog_count INTEGER NOT NULL, manifest JSONB NOT NULL);",
        "CREATE TABLE core_game.catalog_source (release_id TEXT NOT NULL REFERENCES core_game.catalog_release(release_id) ON DELETE CASCADE, source_id TEXT NOT NULL, path TEXT NOT NULL, byte_count BIGINT NOT NULL, sha256 TEXT NOT NULL, PRIMARY KEY (release_id, source_id));",
        "CREATE TABLE core_game.material_market (material_id TEXT PRIMARY KEY, source_index INTEGER NOT NULL UNIQUE, price BIGINT, rating INTEGER, level INTEGER, convert_value INTEGER, compose_value INTEGER, parent_index INTEGER, magic BOOLEAN, payload JSONB NOT NULL);",
        "CREATE TABLE core_game.monster (monster_index INTEGER PRIMARY KEY, area INTEGER NOT NULL, monster_type INTEGER NOT NULL, create_level INTEGER NOT NULL, unique_level INTEGER NOT NULL, race INTEGER NOT NULL, hp BIGINT NOT NULL, damage BIGINT NOT NULL, armor BIGINT NOT NULL, experience BIGINT NOT NULL, gold BIGINT NOT NULL, payload JSONB NOT NULL);",
        "CREATE TABLE core_game.monster_material_drop (monster_index INTEGER NOT NULL REFERENCES core_game.monster(monster_index) ON DELETE CASCADE, slot INTEGER NOT NULL, material_id TEXT NOT NULL, quantity INTEGER NOT NULL, raw_percent INTEGER NOT NULL, PRIMARY KEY (monster_index, slot));",
        "CREATE TABLE core_game.monster_unique_gear_pool (pool_index INTEGER PRIMARY KEY, drop_range BIGINT NOT NULL, drop_cut JSONB NOT NULL, gear_pool JSONB NOT NULL);",
        "CREATE TABLE core_game.recipe_material_input (product_id TEXT NOT NULL, building_id TEXT, slot INTEGER NOT NULL, material_id TEXT NOT NULL, quantity INTEGER NOT NULL, payload JSONB NOT NULL, PRIMARY KEY (product_id, slot));",
        "CREATE TABLE core_game.building_material_cost (row_kind TEXT NOT NULL, building_id TEXT NOT NULL, level INTEGER NOT NULL, slot INTEGER NOT NULL, material_id TEXT NOT NULL, quantity INTEGER NOT NULL, payload JSONB NOT NULL, PRIMARY KEY (row_kind, building_id, level, slot));",
        "CREATE TABLE core_game.unresolved_recipe_condition (product_id TEXT NOT NULL, building_id TEXT, required_evidence TEXT NOT NULL, PRIMARY KEY (product_id, building_id, required_evidence));",
        "CREATE TABLE core_game.experience (row_index INTEGER PRIMARY KEY, experience_by_difficulty JSONB NOT NULL, unresolved_dummy_fields JSONB NOT NULL, payload JSONB NOT NULL);",
        "CREATE TABLE core_game.gear (kind TEXT NOT NULL, item_index INTEGER NOT NULL, job INTEGER NOT NULL, item_group INTEGER NOT NULL, item_level INTEGER NOT NULL, visible INTEGER NOT NULL, sort_group INTEGER NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, icon_path TEXT, prices JSONB NOT NULL, materials_by_rating JSONB NOT NULL, payload JSONB NOT NULL, PRIMARY KEY (kind, item_index));",
        f"INSERT INTO core_game.catalog_release VALUES ('evil-hunter-1.411.core-game-v1', '1.411', 'confirmed-with-unresolved-evidence', 4, {sql_json({'catalogs': ['monster-runtime-catalog.json', 'monster-material-market-catalog.json', 'gear-catalog.json', 'experience-runtime-catalog.json'], 'unresolvedRecipeConditions': len(market['unresolvedRecipeConditions']), 'policy': 'unresolved fields are preserved, never synthesized'})});",
    ]

    for source_id, name, sha in [
        ("monster-runtime", "monster-runtime-catalog.json", monster_sha),
        ("monster-material-market", "monster-material-market-catalog.json", market_sha),
        ("gear", "gear-catalog.json", gear_sha),
        ("experience", "experience-runtime-catalog.json", experience_sha),
    ]:
        path = RELEASE / name
        lines.append(
            "INSERT INTO core_game.catalog_source VALUES "
            f"('evil-hunter-1.411.core-game-v1', {sql_text(source_id)}, {sql_text(str(path.relative_to(ROOT)))}, {path.stat().st_size}, {sql_text(sha)});"
        )

    for material in market["materials"]:
        lines.append(
            "INSERT INTO core_game.material_market VALUES "
            f"({sql_text(material['materialId'])}, {material['sourceIndex']}, {material.get('price') if material.get('price') is not None else 'NULL'}, "
            f"{material.get('rating') if material.get('rating') is not None else 'NULL'}, {material.get('level') if material.get('level') is not None else 'NULL'}, "
            f"{material.get('convert') if material.get('convert') is not None else 'NULL'}, {material.get('compose') if material.get('compose') is not None else 'NULL'}, "
            f"{material.get('parentIndex') if material.get('parentIndex') is not None else 'NULL'}, "
            f"{'TRUE' if material.get('magic') else 'FALSE'}, {sql_json(material)});"
        )

    monster_index = 0
    for group in monster["groups"]:
        key = group["key"]
        for row in group["monsters"]:
            monster_index = max(monster_index, row["index"])
            lines.append(
                "INSERT INTO core_game.monster VALUES "
                f"({row['index']}, {key['area']}, {key['type']}, {key['createLevel']}, {row['uniqueLevel']}, {row['race']}, {row['hp']}, {row['damage']}, {row['armor']}, {row['experience']}, {row['gold']}, {sql_json(row)});"
            )
            materials = row.get("materials", {})
            for slot, (material_id, quantity, percent) in enumerate(zip(materials.get("indices", []), materials.get("counts", []), materials.get("percentValues", []))):
                lines.append(
                    "INSERT INTO core_game.monster_material_drop VALUES "
                    f"({row['index']}, {slot}, {sql_text(f'material:{material_id}')}, {quantity}, {percent});"
                )

    for pool in monster["uniqueGearPools"]:
        lines.append(
            "INSERT INTO core_game.monster_unique_gear_pool VALUES "
            f"({pool['index']}, {pool['dropRange']}, {sql_json(pool['dropCut'])}, {sql_json(pool['gearPool'])});"
        )

    for row in market["recipeMaterialInputs"]:
        lines.append("INSERT INTO core_game.recipe_material_input VALUES "
                     f"({sql_text(row['productId'])}, {sql_text(row['buildingId']) if row.get('buildingId') else 'NULL'}, {row['slot']}, {sql_text(row['materialId'])}, {row['quantity']}, {sql_json(row)});")
    for row in market["buildingMaterialCosts"]:
        lines.append("INSERT INTO core_game.building_material_cost VALUES "
                     f"({sql_text(row['rowKind'])}, {sql_text(row['buildingId'])}, {row['level']}, {row['slot']}, {sql_text(row['materialId'])}, {row['quantity']}, {sql_json(row)});")
    for row in market["unresolvedRecipeConditions"]:
        lines.append("INSERT INTO core_game.unresolved_recipe_condition VALUES "
                     f"({sql_text(row['productId'])}, {sql_text(row['buildingId']) if row.get('buildingId') else 'NULL'}, {sql_text(row['requiredEvidence'])});")

    for row in experience["rows"]:
        lines.append("INSERT INTO core_game.experience VALUES "
                     f"({row['index']}, {sql_json(row['experienceByDifficulty'])}, {sql_json(row['unresolvedDummyFields'])}, {sql_json(row)});")
    for row in gear["rows"]:
        lines.append("INSERT INTO core_game.gear VALUES "
                     f"({sql_text(row['kind'])}, {row['index']}, {row['job']}, {row['group']}, {row['itemLevel']}, {row['visible']}, {row['sortGroup']}, {sql_text(row['name'])}, {sql_text(row['description'])}, {sql_text(row['iconPath'])}, {sql_json(row['prices'])}, {sql_json(row['materialsByRating'])}, {sql_json(row)});")

    lines += [
        "CREATE INDEX core_game_monster_area_idx ON core_game.monster(area, monster_type, create_level);",
        "CREATE INDEX core_game_drop_material_idx ON core_game.monster_material_drop(material_id);",
        "CREATE INDEX core_game_recipe_material_idx ON core_game.recipe_material_input(material_id);",
        "CREATE INDEX core_game_building_cost_material_idx ON core_game.building_material_cost(material_id);",
        "DO $$ BEGIN IF (SELECT count(*) FROM core_game.material_market) <> 179 OR (SELECT count(*) FROM core_game.monster) <> 195 OR (SELECT count(*) FROM core_game.monster_material_drop) <> 1617 OR (SELECT count(*) FROM core_game.monster_unique_gear_pool) <> 61 OR (SELECT count(*) FROM core_game.recipe_material_input) <> 5797 OR (SELECT count(*) FROM core_game.building_material_cost) <> 132 OR (SELECT count(*) FROM core_game.unresolved_recipe_condition) <> 2810 OR (SELECT count(*) FROM core_game.experience) <> 100 OR (SELECT count(*) FROM core_game.gear) <> 671 THEN RAISE EXCEPTION 'core-game catalog count mismatch'; END IF; END $$;",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
